from enum import Enum

# Standardized Enums for the Trading Bot
class TradeAction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"

class Trend(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    SIDEWAYS = "SIDEWAYS"

class BrokerType(str, Enum):
    GROWW = "GROWW"
    YFINANCE = "YFINANCE"
    MOCK = "MOCK"

# The Master F&O Universe List (Constant)
# Tum isme apne hisaab se aur stocks add kar sakte ho
# FNO_UNIVERSE = [
#     "RELIANCE", "HDFCBANK", "ICICIBANK", "INFY", "TCS",
#     "SBIN", "BHARTIARTL", "ITC", "KOTAKBANK", "LT",
#     "AXISBANK", "BAJFINANCE", "MARUTI", "ASIANPAINT", "BAJAJ-AUTO", "EICHERMOT", 'PIDILITIND', 'TVSMOTOR', 'CIPLA', ]

FNO_UNIVERSE = [
    "RELIANCE", "TCS", "HDFCBANK", "ICICIBANK", "INFY", "SBIN", "BHARTIARTL", "ITC",
    "KOTAKBANK", "LT", "HINDUNILVR", "AXISBANK", "MARUTI", "SUNPHARMA", "ULTRACEMCO",
    "TATAMOTORS", "NTPC", "TITAN", "POWERGRID", "BAJFINANCE", "ONGC", "M&M",
    "TATASTEEL", "JSWSTEEL", "COALINDIA", "BAJAJFINSV", "HCLTECH", "ASIANPAINT",
    "ADANIENT", "ADANIPORTS", "TATACONSUM", "GRASIM", "WIPRO", "TECHM", "HINDALCO",
    "CIPLA", "EICHERMOT", "APOLLOHOSP", "DIVISLAB", "DRREDDY", "SBILIFE", "HDFCLIFE",
    "BRITANNIA", "INDUSINDBK", "BAJAJ-AUTO", "TATAPOWER", "GAIL", "BPCL", "IOC",
    "SHREECEM", "HEROMOTOCO", "TRENT", "BEL", "HAL", "CHOLAFIN", "INDIGO", "VEDL",
    "TVSMOTOR", "DLF", "BANKBARODA", "PNB", "CANBK", "ZOMATO", "TORNTPHARM",
    "LTIM", "HAVELLS", "CUMMINSIND", "PIDILITIND", "SIEMENS", "BOSCHLTD", "ABB",
    "AMBUJACEM", "MCDOWELL-N", "TATACHEM", "UPL", "AUROPHARMA", "LUPIN", "BIOCON",
    "GODREJCP", "DABUR", "MARICO", "COLPAL", "PETRONET", "IGL", "MGL", "TATACOMM",
    "INDHOTEL", "IRCTC", "PFC", "RECLTD", "NAUKRI", "MUTHOOTFIN", "SHRIRAMFIN",
    "ICICIPRULI", "AUBANK", "FEDERALBNK", "IDFCFIRSTB", "BANDHANBNK", "BATAINDIA", "VOLTAS"
]
