from enum import Enum


# Standardized Enums for the Trading Bot
class TradeAction(str, Enum):
    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


class Trend(str, Enum):
    BULLISH = "BULLISH"
    BEARISH = "BEARISH"
    SIDEWAYS = "SIDEWAYS"


class BrokerType(str, Enum):
    GROWW = "GROWW"
    YFINANCE = "YFINANCE"
    MOCK = "MOCK"


# The Master F&O Universe List (Constant)
# Tum isme apne hisaab se aur stocks add kar sakte ho
# FNO_UNIVERSE = [
#     "RELIANCE", "HDFCBANK", "ICICIBANK", "INFY", "TCS",
#     "SBIN", "BHARTIARTL", "ITC", "KOTAKBANK", "LT",
#     "AXISBANK", "BAJFINANCE", "MARUTI", "ASIANPAINT", "BAJAJ-AUTO", "EICHERMOT", 'PIDILITIND', 'TVSMOTOR', 'CIPLA', ]

FNO_UNIVERSE = [
    "RELIANCE", "HDFCBANK", "ICICIBANK", "INFY", "TCS", "SBIN", "BHARTIARTL", "AXISBANK", "LT", "ITC",
    "KOTAKBANK", "HINDUNILVR", "BAJFINANCE", "M&M", "SUNPHARMA", "MARUTI", "TMPV", "ADANIENT", "ADANIPORTS",
    "TITAN",
    "ASIANPAINT", "ULTRACEMCO", "NTPC", "POWERGRID", "HCLTECH", "ONGC", "JSWSTEEL", "TATASTEEL", "COALINDIA",
    "BAJAJFINSV",
    "GRASIM", "ADANIPOWER", "HINDALCO", "NESTLEIND", "BRITANNIA", "TECHM", "EICHERMOT", "SBILIFE", "WIPRO", "CIPLA",
    "BPCL", "BAJAJ-AUTO", "HDFCLIFE", "APOLLOHOSP", "TATACONSUM", "DRREDDY", "DIVISLAB", "LTM", "ADANIGREEN", "JIOFIN",
    "ETERNAL", "SHRIRAMFIN", "GRASIM", "BEL", "HAL", "BHEL", "DLF", "RECLTD", "PFC", "CHOLAFIN",
    "TVSMOTOR", "HEROMOTOCO", "INDUSINDBK", "CANBK", "BANKBARODA", "PNB", "IDFCFIRSTB", "YESBANK", "BANDHANBNK",
    "FEDERALBNK",
    "AUBANK", "LICI", "SBICARD", "MOTILALOFS", "ANGELONE", "BSE", "MCX", "CDSL", "CAMS", "NYKAA",
    "PAYTM", "POLICYBZR", "DELHIVERY", "DMART", "HYUNDAI", "SWIGGY", "WAAREEENER", "PREMIERENE", "TRENT", "DIXON",
    "AUBANK", "PERSISTENT", "COFORGE", "MPHASIS", "LTTS", "KPITTECH", "TATAELXSI", "TATAELXSI", "BSOFT", "OFSS",
    "SUNTV", "PAGEIND", "COLPAL", "DABUR", "MARICO", "GODREJCP", "UNITDSPR", "UPL", "COROMANDEL", "PIIND",
    "SRF", "PIDILITIND", "BERGEPAINT", "HAVELLS", "VOLTAS", "POLYCAB", "KEI", "AMBUJACEM", "ACC", "DALBHARAT",
    "JKCEMENT", "OBEROIRLTY", "GODREJPROP", "PRESTIGE", "LODHA", "GMRINFRA", "IRFC", "RVNL", "SJVN", "NHPC",
    "IRCTC", "CONCOR", "IOC", "HINDPETRO", "GAIL", "PETRONET", "OIL", "IGL", "MGL", "TORNTPHARM",
    "AUROPHARMA", "LUPIN", "BIOCON", "ALKEM", "ZYDUSLIFE", "MAXHEALTH", "MANKIND", "GLENMARK", "IPCALAB", "ABBOTINDIA"
]
# FNO_UNIVERSE = ["HEROMOTOCO", "LUPIN"]
